# Generated by Django 5.1.4 on 2024-12-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('novel_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('novel_name', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('intro', models.TextField()),
                ('novel_img_link', models.CharField(max_length=255)),
                ('rating', models.FloatField(db_column='Rating')),
                ('action', models.IntegerField(db_column='Action')),
                ('adventure', models.IntegerField(db_column='Adventure')),
                ('fantasy', models.IntegerField(db_column='Fantasy')),
                ('isekai', models.IntegerField(db_column='Isekai')),
                ('slice_of_life', models.IntegerField(db_column='Slice_of_Life')),
                ('read_count', models.IntegerField(db_column='Read_Count')),
            ],
            options={
                'db_table': 'novel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NovelChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_id', models.PositiveBigIntegerField()),
                ('cpt_no', models.BigIntegerField()),
                ('chapter_title', models.CharField(max_length=255)),
                ('cpt_text', models.TextField()),
                ('descript_id', models.IntegerField(db_column='Descript_ID')),
            ],
            options={
                'db_table': 'novel_chapter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
