# Generated by Django 5.1.4 on 2025-01-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_readhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('novel_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(db_column='Author', max_length=255)),
            ],
            options={
                'db_table': 'authors',
                'managed': False,
            },
        ),
    ]
